### ISSUE TITLE
关于镜像静态网页的方法

### ISSUE THREAD

**Issue by InsideEmpire** [hqhq1025/cs61a-24fa-backup#1]
您好，我想知道您是通过什么方法，或是什么工具能够将静态网页的所有资源下载到本地的😀

**Comment by hqhq1025** [comment]
<img width="920" alt="image" src="https://github.com/user-attachments/assets/cbbef318-9141-4acb-bba2-5242a746adc6">
您好 我其实也是查的gpt，用的是wget指令 这里具体用的是图片里的这一条 应该是全的

**Comment by hqhq1025** [comment]
<img width="508" alt="image" src="https://github.com/user-attachments/assets/29d73242-83a3-4f56-b013-b140490f4863">

**Comment by InsideEmpire** [comment]
好的十分感谢
